#############################################################################
# Generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#  Nov 25, 2018 08:23:41 PM CET  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

#############################################################################
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m56" -background {#d9d9d9} 
    wm focusmodel $top passive
    wm geometry $top 945x847+309+85
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 4644 1243
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "ETO design"
    vTcl:DefineAlias "$top" "Toplevel_design" vTcl:Toplevel:WidgetProc "" 1
    label $top.lab44 \
        -background {#a6d3d8} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} -text {Query by element ID} 
    vTcl:DefineAlias "$top.lab44" "Label1" vTcl:WidgetProc "Toplevel_design" 1
    button $top.but45 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Displaying all ETO materials} 
    vTcl:DefineAlias "$top.but45" "Button1" vTcl:WidgetProc "Toplevel_design" 1
    entry $top.ent46 \
        -background white -disabledforeground {#a3a3a3} -font font10 \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$top.ent46" "Entry1" vTcl:WidgetProc "Toplevel_design" 1
    label $top.lab47 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#a6d3d8} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Query by task ID} 
    vTcl:DefineAlias "$top.lab47" "Label1_1" vTcl:WidgetProc "Toplevel_design" 1
    button $top.but48 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 -text Go 
    vTcl:DefineAlias "$top.but48" "Button2" vTcl:WidgetProc "Toplevel_design" 1
    entry $top.ent50 \
        -background white -disabledforeground {#a3a3a3} -font font10 \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$top.ent50" "Entry2" vTcl:WidgetProc "Toplevel_design" 1
    button $top.but51 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 -text Go 
    vTcl:DefineAlias "$top.but51" "Button3" vTcl:WidgetProc "Toplevel_design" 1
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $top.scr53 \
        -background {#d9d9d9} -height 75 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 921 
    vTcl:DefineAlias "$top.scr53" "Scrolledlistbox1" vTcl:WidgetProc "Toplevel_design" 1

    $top.scr53.01 configure -background white \
        -disabledforeground #a3a3a3 \
        -font font10 \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $top.scr54 \
        -background {#d9d9d9} -height 205 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 921 
    vTcl:DefineAlias "$top.scr54" "Scrolledlistbox2" vTcl:WidgetProc "Toplevel_design" 1

    $top.scr54.01 configure -background white \
        -disabledforeground #a3a3a3 \
        -font font10 \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10
    set site_3_0 $top.m56
    menu $site_3_0 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -font font9 -foreground {#000000} -tearoff 0 
    labelframe $top.lab63 \
        -font TkDefaultFont -foreground black -text {Design Changes} \
        -background {#d9d9d9} -height 435 -width 920 
    vTcl:DefineAlias "$top.lab63" "Labelframe1" vTcl:WidgetProc "Toplevel_design" 1
    set site_3_0 $top.lab63
    label $site_3_0.lab65 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#a6d3d8} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Design change request ID} 
    vTcl:DefineAlias "$site_3_0.lab65" "Label1_4" vTcl:WidgetProc "Toplevel_design" 1
    entry $site_3_0.ent66 \
        -background white -disabledforeground {#a3a3a3} -font font10 \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent66" "Entry3" vTcl:WidgetProc "Toplevel_design" 1
    button $site_3_0.but67 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Update the changed design parameters} 
    vTcl:DefineAlias "$site_3_0.but67" "Button4" vTcl:WidgetProc "Toplevel_design" 1
    button $site_3_0.but70 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {View from design drawings} 
    vTcl:DefineAlias "$site_3_0.but70" "Button5" vTcl:WidgetProc "Toplevel_design" 1
    label $site_3_0.lab71 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} -text {Revit 2D drawings} 
    vTcl:DefineAlias "$site_3_0.lab71" "Label2" vTcl:WidgetProc "Toplevel_design" 1
    label $site_3_0.lab72 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#a6d3d8} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Select design parameter} 
    vTcl:DefineAlias "$site_3_0.lab72" "Label1_5" vTcl:WidgetProc "Toplevel_design" 1
    entry $site_3_0.ent74 \
        -background white -disabledforeground {#a3a3a3} -font font10 \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent74" "Entry4" vTcl:WidgetProc "Toplevel_design" 1
    place $site_3_0.lab65 \
        -in $site_3_0 -x 10 -y 20 -width 274 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent66 \
        -in $site_3_0 -x 300 -y 20 -width 124 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but67 \
        -in $site_3_0 -x 10 -y 90 -width 267 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but70 \
        -in $site_3_0 -x 450 -y 20 -width 287 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab71 \
        -in $site_3_0 -x 460 -y 60 -width 434 -relwidth 0 -height 351 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab72 \
        -in $site_3_0 -x 10 -y 60 -width 274 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent74 \
        -in $site_3_0 -x 300 -y 60 -width 124 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $top.scr69 \
        -background {#d9d9d9} -height 295 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 421 
    vTcl:DefineAlias "$top.scr69" "Scrolledlistbox2_7" vTcl:WidgetProc "Toplevel_design" 1

    $top.scr69.01 configure -background white \
        -disabledforeground #a3a3a3 \
        -font font10 \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab44 \
        -in $top -x 10 -y 40 -width 274 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but45 \
        -in $top -x 10 -y 10 -width 277 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent46 \
        -in $top -x 300 -y 40 -width 264 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 10 -y 160 -width 274 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.but48 \
        -in $top -x 580 -y 40 -anchor nw -bordermode ignore 
    place $top.ent50 \
        -in $top -x 300 -y 160 -width 264 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but51 \
        -in $top -x 580 -y 160 -anchor nw -bordermode ignore 
    place $top.scr53 \
        -in $top -x 10 -y 70 -width 921 -relwidth 0 -height 75 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.scr54 \
        -in $top -x 10 -y 190 -width 921 -relwidth 0 -height 205 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab63 \
        -in $top -x 10 -y 400 -width 920 -relwidth 0 -height 435 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.scr69 \
        -in $top -x 20 -y 530 -width 421 -relwidth 0 -height 295 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

