#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#    Dec 08, 2018 10:26:57 AM CET  platform: Windows NT

import _constants
today = _constants.Current_date()

import datetime
from datetime import timedelta
import pandas as pd
import sqlite3
from tkinter import messagebox
from tkinter import *
import time


pd.set_option('display.max_columns', 500)

conn = sqlite3.connect(
    'C:\\Users\\chenqi\\polybox\\Qian\\1 Doctoral Research\\16.02-AMF\\P6 GUI development\\data\\Aturm.sqlite')
cur = conn.cursor()

df_MP = pd.read_sql_query('select * from manufacturing_process', conn)
df_ETOs = pd.read_sql_query('select * from Structural_Column_Material_Takeoff', conn)
df_changes_field = pd.read_sql_query('select * from changes_field', conn)
df_changes_production = pd.read_sql_query('select * from changes_production', conn)
df_tasks = pd.read_sql_query('select * from Tasks', conn)
df_inspection = pd.read_sql_query('select * from inspection', conn)
df_reship = pd.read_sql_query('select * from reship', conn)



import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Reship_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    Reship_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    Reship_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#ececec' # Closest X11 color: 'gray92' 
        font10 = "-family {Courier New} -size 10 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("905x519+369+225")
        top.title("Re-ship")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")
        top.wm_iconbitmap('logo.ico')


        def show_defects():
            self.Scrolledlistbox1.delete('0', 'END')

            tree = ttk.Treeview(self.Scrolledlistbox1,columns = (1,2,3,4,5),show = 'headings')
            tree.heading(1, text='RFID')
            tree.heading(2, text='Family and Type')
            tree.heading(3, text='Defect')
            tree.heading(4, text='Inspection Staff')
            tree.heading(5, text='Inspection Date')
            tree.pack()
            scroll = ttk.Scrollbar(self.Scrolledlistbox1, orient="vertical", command=tree.yview)
            tree.configure(yscrollcommand=scroll.set)


            for i in range(len(df_inspection)):
                if df_inspection.loc[i,'quality_check'] == 'Fail':
                    tree.insert('','end', values=(df_inspection.loc[i, 'RFID'], df_inspection.loc[i,'Family']+' '+df_inspection.loc[i,'Type'], df_inspection.loc[i, 'defect'],
                                                  df_inspection.loc[i,'inspect_staff'], df_inspection.loc[i, 'inspect_date']))

        self.Button1 = tk.Button(top, command=show_defects)
        self.Button1.place(relx=0.011, rely=0.019, height=24, width=267)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Show all the defect elements''')
        self.Button1.configure(width=267)

        self.Scrolledlistbox1 = ScrolledListBox(top)
        self.Scrolledlistbox1.place(relx=0.011, rely=0.077, relheight=0.279
                , relwidth=0.973)
        self.Scrolledlistbox1.configure(background="white")
        self.Scrolledlistbox1.configure(disabledforeground="#a3a3a3")
        self.Scrolledlistbox1.configure(font=font10)
        self.Scrolledlistbox1.configure(foreground="black")
        self.Scrolledlistbox1.configure(highlightbackground="#d9d9d9")
        self.Scrolledlistbox1.configure(highlightcolor="#d9d9d9")
        self.Scrolledlistbox1.configure(selectbackground="#c4c4c4")
        self.Scrolledlistbox1.configure(selectforeground="black")
        self.Scrolledlistbox1.configure(width=10)

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.011, rely=0.385, height=21, width=184)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d8c2cf")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Input RFID''')

        self.Entry1 = tk.Entry(top)
        self.Entry1.place(relx=0.232, rely=0.385,height=20, relwidth=0.303)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font=font10)
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(selectbackground="#c4c4c4")
        self.Entry1.configure(selectforeground="black")


        def query_defect():
            self.Scrolledlistbox1_4.delete('0', 'END')
            RFID = self.Entry1.get()

            tree = ttk.Treeview(self.Scrolledlistbox1_4, columns=(1, 2, 3, 4, 5, 6), show='headings')
            tree.heading(1, text='RFID')
            tree.heading(2, text='Family and Type')
            tree.heading(3, text='Defect')
            tree.heading(4, text='Inspection Staff')
            tree.heading(5, text='Inspection Date')
            tree.heading(6, text='Certification')
            tree.pack()
            scroll = ttk.Scrollbar(self.Scrolledlistbox1_4, orient="vertical", command=tree.yview)
            tree.configure(yscrollcommand=scroll.set)

            for i in range(len(df_inspection)):
                if df_inspection.loc[i, 'RFID'] == RFID:
                    tree.insert('', 'end', values=(
                    df_inspection.loc[i, 'RFID'], df_inspection.loc[i, 'Family'] + ' ' + df_inspection.loc[i, 'Type'],
                    df_inspection.loc[i, 'defect'],
                    df_inspection.loc[i, 'inspect_staff'], df_inspection.loc[i, 'inspect_date'], df_inspection.loc[i, 'certification']))

        self.Button2 = tk.Button(top,command=query_defect)
        self.Button2.place(relx=0.232, rely=0.443, height=24, width=277)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Show the defects''')

        self.Label1_1 = tk.Label(top)
        self.Label1_1.place(relx=0.011, rely=0.713, height=21, width=184)
        self.Label1_1.configure(activebackground="#f9f9f9")
        self.Label1_1.configure(activeforeground="black")
        self.Label1_1.configure(background="#d8c2cf")
        self.Label1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1.configure(foreground="#000000")
        self.Label1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1.configure(highlightcolor="black")
        self.Label1_1.configure(text='''Input re-shipping date''')

        self.Entry1_2 = tk.Entry(top)
        self.Entry1_2.place(relx=0.232, rely=0.713,height=20, relwidth=0.303)
        self.Entry1_2.configure(background="white")
        self.Entry1_2.configure(disabledforeground="#a3a3a3")
        self.Entry1_2.configure(font=font10)
        self.Entry1_2.configure(foreground="#000000")
        self.Entry1_2.configure(highlightbackground="#d9d9d9")
        self.Entry1_2.configure(highlightcolor="black")
        self.Entry1_2.configure(insertbackground="black")
        self.Entry1_2.configure(selectbackground="#c4c4c4")
        self.Entry1_2.configure(selectforeground="black")

        self.Scrolledlistbox1_4 = ScrolledListBox(top)
        self.Scrolledlistbox1_4.place(relx=0.011, rely=0.501, relheight=0.202
                , relwidth=0.973)
        self.Scrolledlistbox1_4.configure(background="white")
        self.Scrolledlistbox1_4.configure(disabledforeground="#a3a3a3")
        self.Scrolledlistbox1_4.configure(font=font10)
        self.Scrolledlistbox1_4.configure(foreground="black")
        self.Scrolledlistbox1_4.configure(highlightbackground="#d9d9d9")
        self.Scrolledlistbox1_4.configure(highlightcolor="#d9d9d9")
        self.Scrolledlistbox1_4.configure(selectbackground="#c4c4c4")
        self.Scrolledlistbox1_4.configure(selectforeground="black")
        self.Scrolledlistbox1_4.configure(width=10)

        self.Label1_2 = tk.Label(top)
        self.Label1_2.place(relx=0.011, rely=0.771, height=21, width=184)
        self.Label1_2.configure(activebackground="#f9f9f9")
        self.Label1_2.configure(activeforeground="black")
        self.Label1_2.configure(background="#d8c2cf")
        self.Label1_2.configure(disabledforeground="#a3a3a3")
        self.Label1_2.configure(foreground="#000000")
        self.Label1_2.configure(highlightbackground="#d9d9d9")
        self.Label1_2.configure(highlightcolor="black")
        self.Label1_2.configure(text='''Responsible supplier''')

        self.Entry1_3 = tk.Entry(top)
        self.Entry1_3.place(relx=0.232, rely=0.771,height=20, relwidth=0.303)
        self.Entry1_3.configure(background="white")
        self.Entry1_3.configure(disabledforeground="#a3a3a3")
        self.Entry1_3.configure(font=font10)
        self.Entry1_3.configure(foreground="#000000")
        self.Entry1_3.configure(highlightbackground="#d9d9d9")
        self.Entry1_3.configure(highlightcolor="black")
        self.Entry1_3.configure(insertbackground="black")
        self.Entry1_3.configure(selectbackground="#c4c4c4")
        self.Entry1_3.configure(selectforeground="black")

        option = StringVar()

        self.Radiobutton1 = tk.Radiobutton(top, value='1', variable=option)
        self.Radiobutton1.place(relx=0.276, rely=0.829, relheight=0.06
                                , relwidth=0.056)
        self.Radiobutton1.configure(activebackground="#ececec")
        self.Radiobutton1.configure(activeforeground="#000000")
        self.Radiobutton1.configure(background="#d9d9d9")
        self.Radiobutton1.configure(disabledforeground="#a3a3a3")
        self.Radiobutton1.configure(foreground="#000000")
        self.Radiobutton1.configure(highlightbackground="#d9d9d9")
        self.Radiobutton1.configure(highlightcolor="black")
        self.Radiobutton1.configure(justify='left')
        self.Radiobutton1.configure(text='''Yes''')

        self.Radiobutton2 = tk.Radiobutton(top, value='0', variable=option)
        self.Radiobutton2.place(relx=0.409, rely=0.829, relheight=0.06
                                , relwidth=0.054)
        self.Radiobutton2.configure(activebackground="#ececec")
        self.Radiobutton2.configure(activeforeground="#000000")
        self.Radiobutton2.configure(background="#d9d9d9")
        self.Radiobutton2.configure(disabledforeground="#a3a3a3")
        self.Radiobutton2.configure(foreground="#000000")
        self.Radiobutton2.configure(highlightbackground="#d9d9d9")
        self.Radiobutton2.configure(highlightcolor="black")
        self.Radiobutton2.configure(justify='left')
        self.Radiobutton2.configure(text='''No''')

        def update_reship():
            RFID = self.Entry1.get()
            reship_date = self.Entry1_2.get()
            reship_supplier = self.Entry1_3.get()
            replace = option.get()

            for i in range(len(df_reship)):
                if df_reship.loc[i, 'RFID'] == RFID:
                    df_reship.loc[i, 'reship_date']=reship_date
                    df_reship.loc[i, 'reship_supplier']=reship_supplier
                    if replace == '1':
                        df_reship.loc[i, 'replacement'] = 'Y'
                    elif replace == '0':
                        df_reship.loc[i, 'replacement'] = 'N'
                    else:
                        pass
                else:
                    pass
            df_reship.to_sql('reship', conn, if_exists='replace', index=False)

        self.Button2_4 = tk.Button(top, command=update_reship)
        self.Button2_4.place(relx=0.232, rely=0.925, height=24, width=277)
        self.Button2_4.configure(activebackground="#ececec")
        self.Button2_4.configure(activeforeground="#000000")
        self.Button2_4.configure(background="#d9d9d9")
        self.Button2_4.configure(disabledforeground="#a3a3a3")
        self.Button2_4.configure(foreground="#000000")
        self.Button2_4.configure(highlightbackground="#d9d9d9")
        self.Button2_4.configure(highlightcolor="black")
        self.Button2_4.configure(pady="0")
        self.Button2_4.configure(text='''Update''')

        self.Label1_3 = tk.Label(top)
        self.Label1_3.place(relx=0.011, rely=0.829, height=31, width=184)
        self.Label1_3.configure(activebackground="#f9f9f9")
        self.Label1_3.configure(activeforeground="black")
        self.Label1_3.configure(background="#d8c2cf")
        self.Label1_3.configure(disabledforeground="#a3a3a3")
        self.Label1_3.configure(foreground="#000000")
        self.Label1_3.configure(highlightbackground="#d9d9d9")
        self.Label1_3.configure(highlightcolor="black")
        self.Label1_3.configure(text='''Immediate replacement?''')
        self.Label1_3.configure(width=184)



# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''

    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)

        #self.configure(yscrollcommand=_autoscroll(vsb),
        #    xscrollcommand=_autoscroll(hsb))
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))

        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')

        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)

        # Copy geometry methods of master  (taken from ScrolledText.py)
        if py3:
            methods = tk.Pack.__dict__.keys() | tk.Grid.__dict__.keys() \
                  | tk.Place.__dict__.keys()
        else:
            methods = tk.Pack.__dict__.keys() + tk.Grid.__dict__.keys() \
                  + tk.Place.__dict__.keys()

        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        container.bind('<Enter>', lambda e: _bound_to_mousewheel(e, container))
        container.bind('<Leave>', lambda e: _unbound_to_mousewheel(e, container))
        return func(cls, container, **kw)
    return wrapped

class ScrolledListBox(AutoScroll, tk.Listbox):
    '''A standard Tkinter Text widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        tk.Listbox.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)

import platform
def _bound_to_mousewheel(event, widget):
    child = widget.winfo_children()[0]
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        child.bind_all('<MouseWheel>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-MouseWheel>', lambda e: _on_shiftmouse(e, child))
    else:
        child.bind_all('<Button-4>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Button-5>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-Button-4>', lambda e: _on_shiftmouse(e, child))
        child.bind_all('<Shift-Button-5>', lambda e: _on_shiftmouse(e, child))

def _unbound_to_mousewheel(event, widget):
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        widget.unbind_all('<MouseWheel>')
        widget.unbind_all('<Shift-MouseWheel>')
    else:
        widget.unbind_all('<Button-4>')
        widget.unbind_all('<Button-5>')
        widget.unbind_all('<Shift-Button-4>')
        widget.unbind_all('<Shift-Button-5>')

def _on_mousewheel(event, widget):
    if platform.system() == 'Windows':
        widget.yview_scroll(-1*int(event.delta/120),'units')
    elif platform.system() == 'Darwin':
        widget.yview_scroll(-1*int(event.delta),'units')
    else:
        if event.num == 4:
            widget.yview_scroll(-1, 'units')
        elif event.num == 5:
            widget.yview_scroll(1, 'units')

def _on_shiftmouse(event, widget):
    if platform.system() == 'Windows':
        widget.xview_scroll(-1*int(event.delta/120), 'units')
    elif platform.system() == 'Darwin':
        widget.xview_scroll(-1*int(event.delta), 'units')
    else:
        if event.num == 4:
            widget.xview_scroll(-1, 'units')
        elif event.num == 5:
            widget.xview_scroll(1, 'units')

if __name__ == '__main__':
    vp_start_gui()





